Repository scheduleonce/knowledgeowl-angular, pull requests merged in 2022-07, with the labels that each got.

#86 reverted the commands
  package.json
Labels: approved, size/XS

#89 Updated the Readme file for knowledgeowl
  package.json
  src/README.md
Labels: approved, size/L

#91 Fixing package publish issue
  package.json
  src/README.md
  src/package-lock.json
  src/package.json
Labels: approved, size/L

#92 Technocrats/oncehub 56291 master
  .gitignore
  package.json
  src/README.md
  src/package-lock.json
  src/package.json
Labels: approved, size/L

#94 Vulnerability fixes
  CHANGELOG.md
  package-lock.json
  package.json
  src/package-lock.json
  src/package.json
Labels: approved, size/XXL

#95 Ultragroots/ONCEHUB-49478 adding merge status to staging-app2
  .lighthouse/jenkins-x/pullrequest.yaml
Labels: size/S, approved
