Repository scheduleonce/knowledgeowl-angular, pull requests merged in 2022-04, with the labels that each got.

#72 Revert "Released 4.0.1-beta.1"
  deploy.sh
  package-deploy/npm-login.js
  package-lock.json
  package.json
Labels: size/S

#75 [TEAM-BETA] ONCEHUB-52876, ONCEHUB-53134, ONCEHUB-53135, ONCEHUB-53136: minimist and nodeforge package update
  package-lock.json
  package.json
  src/package.json
Labels: size/S, approved

#78 updating branch to publish from master
  .lighthouse/jenkins-x/triggers.yaml
Labels: approved, size/XS

#77 ONCEHUB-52876, ONCEHUB-53134, ONCEHUB-53135, ONCEHUB-53136: minimist and nodeforge package update
  package-lock.json
  package.json
  src/package.json
Labels: approved, size/XXL

#79 https://scheduleonce.atlassian.net/browse/ONCEHUB-53279
  .lighthouse/jenkins-x/release.yaml
  deploy.sh
Labels: size/S, approved

#80 updated code to publish package for specific branch
  deploy.sh
Labels: approved, size/XS

#82 Vulnerability fixes
  CHANGELOG.md
  package-lock.json
  package.json
Labels: approved, size/L

#83 Updated package-lock
  package-lock.json
Labels: approved, size/XS
