Repository scheduleonce/knowledgeowl-angular, pull requests merged in 2022-03, with the labels that each got.

#66 [Team-BETA Version] ONCEHUB-52876: minimist and node-forge vulnerability fix
  package-lock.json
  package.json
Labels: size/M, approved

#67 https://scheduleonce.atlassian.net/browse/ONCEHUB-52065
  deploy.sh
  package-deploy/npm-login.js
  package-lock.json
Labels: approved, size/XXL

#70 changed version to release new package version
  package-lock.json
  package.json
Labels: approved, size/XS

#71 Released 4.0.1-beta.1
  deploy.sh
  package-deploy/npm-login.js
  package-lock.json
  package.json
Labels: size/S, approved
