Repository scheduleonce/knowledgeowl-angular, pull requests merged in 2023-06, with the labels that each got.

#115 Vulnerability fixes
  CHANGELOG.md
  package-lock.json
  package.json
  src/package-lock.json
  src/package.json
Labels: approved, size/L

#117 Knowledge Owl Angular version upgrade from v14 to v15
  .gitignore
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  CHANGELOG.md
  angular.json
  deploy.sh
  package-lock.json
  package.json
  src/README.md
  src/package-lock.json
  src/package.json
  src/tsconfig.lib.json
  test/test.ts
  tsconfig.json
Labels: approved, size/XXL

#118 updated node version from 16 to 18.16.0
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS
