Repository scheduleonce/knowledgeowl-angular, pull requests merged in 2023-09, with the labels that each got.

#124 [fixed] vulnerability found in package @adobe/css-tools
  package-lock.json
Labels: size/S

#125 upgraded version
  package-lock.json
  package.json
Labels: size/XS

#126 ONCEHUB-65303 Upgade Angular to v16
  CHANGELOG.md
  package-lock.json
  package.json
  src/package-lock.json
  src/package.json
Labels: size/S, approved
