Repository scheduleonce/knowledgeowl-angular, pull requests merged in 2023-07, with the labels that each got.

#119 Vulnerability fix
  CHANGELOG.md
  package-lock.json
  package.json
  src/package-lock.json
  src/package.json
Labels: approved, size/XXL

#120 Vulnerbaility fix
  deploy.sh
Labels: approved, size/XS

#121 ONCEHUB-65303 Upgrade angular version to 16.x
  CHANGELOG.md
  package-lock.json
  package.json
  src/package-lock.json
  src/package.json
Labels: approved, size/XXL

#122 ONCEHUB-65303 Upgrade angular version to 16.x
  package-lock.json
  package.json
  src/package-lock.json
  src/package.json
Labels: approved, size/XXL

#123 Vulnerability fixe
  CHANGELOG.md
  package-lock.json
  package.json
  src/package-lock.json
  src/package.json
Labels: approved, size/L
