Repository scheduleonce/knowledgeowl-angular, pull requests merged in 2024-08, with the labels that each got.

#153 fixed the vulnerability and updated the version
  package-lock.json
  package.json
Labels: approved, size/L

#155 Update team/pythons branch from qa
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/npm-publish.yml
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  .travis.yml
  CHANGELOG.md
  LICENSE
  README.md
  deploy.sh
  package-deploy/npm-login.js
  package-lock.json
  package.json
Labels: approved, size/XXL

#156 Upgrade Angular version of knowledgeowl-angular to 18
  package-lock.json
  package.json
Labels: approved, size/XXL

#157 chrore: npm audit fix
  package-lock.json
Labels: approved, size/L

#158 Pythons/oncehub 80475 team
  package-lock.json
  package.json
Labels: approved, size/XXL

#159 chore: Did updated in npm-publish.yml file. Update package version to 5.0.0-beta.3
  .github/workflows/npm-publish.yml
  package-lock.json
  package.json
Labels: approved, size/XS

#161 chore: Update package version to 5.0.0-beta.5
  package.json
  src/package.json
Labels: approved, size/XS
